module AdventOfCode2022_Day03

open NUnit.Framework

let input =
    [|
        "GGVGlqWFgVfFqqVZGFlblJPMsDbbMrDMpDsJRn"
        "LwzHtwdLHHwDrzPZzzsJbJ"
        "wdLTBvSvHvZVGCjhfN"
        "HsSSnZVHjjssZnJpSJjBHHWgQGcgqqQLQdQFqNgWgqGNDg"
        "rmmRwrtfThtTrbCrGGGcLBDTqDBNQLdL"
        "mwPrrbzPfwvbzhwMMnnjHnBjZlnzMM"
        "gjjdMBgdqdTpJpBcjgRRRlqnvrqfnZtrtZDw"
        "zHShWLhCszCWHVbVzQWCPtQvNZRwtfftfNnrnftlfR"
        "PzPSssHbVhCLFMJFcMFJJMjdJw"
        "ZqJdtpfpjmpJjpnwWdttTCDLLTQFNTzTzrcqrQqc"
        "MsSlBGvBsSGGSlbGsCgggNTgzNLczFQNrNQVQcFzFF"
        "sGHHSGllhvMGhSRGCjtjtjnjnnmHWpWWtJ"
        "tMdjQlHPHsGjsCtsCpwwqfhfnnFMDMrpfD"
        "SbNvWvBRJRWwFSgppgSrfg"
        "RNcNbvzJRcVLRVzTRFLjdHCQttdZdPlHstPl"
        "QWqgpdBflpHNCNWNHHPm"
        "VVMbbJsLFVMhrMJMmRjFNHwHjjCTGSSRFj"
        "mbMsZzsLmVhJZrcLcJhLMtnqvBnZdggplDffvlnlvnDn"
        "prnNnsFnZpnBNdNtFrNnzNQQwTTQZqTHTQJQMwHDMDlZ"
        "jgfgcSmbLmhmcPShghRdmwJTQjTlqGlJQJHqQqGHqQ"
        "hRVhPfbCgbVggLVRSSmRhRPhrrrnCzzsvCvrnvFnNppsvBtd"
        "QJLNDWSWQdLFFFhLdt"
        "npHhHMsfsjpZjznRtmrMCdBwFBFrBdmt"
        "HsjHqRRfnnHRsgfHffZspgzqDGQSWbQTDNGhQhSqNPhDWWbT"
        "bsCmFDsGZCNsDmLDLZBSHSJTHnrZQMQSSQ"
        "jqRpwvfqnnRQrftdBMHddB"
        "phpchwpzjpvwRzwcsnlFsssPCCGzDlsD"
        "rMqzVQfrfVZWZhTdRTQL"
        "cgmtFtjFFJDDtFvSFRZdLlhpHZddmwTZWh"
        "FbcSTtctcvFTJNgtJDGNPnCqMPMfMBfznGVsrMCq"
        "wLJfGJJPZLBfwSLGHbqmhhDHHhFDzfhv"
        "FsnpFjVjplTQCspNlCDbzhMMbqvMvsgmHDqb"
        "lRdlTdTddllpRQFRltVVdFRcwrtrcWWcPrrWPrPSrZWLPc"
        "VGVZhTppGTfPnJVJrFqbsmbSSshHqWqRHF"
        "llzDCzlBLdNcCddlMMNBdCCtWHbFqFRRRsHjWtRwSWqbmjWm"
        "NbcMBBvzzMQLCDBVTQQPVrPQPPZVPp"
        "cdcgfmQdqlqhzzPjzfwpwf"
        "GLBGBDvbvRzGwtnnmPpp"
        "ZRCZBRFSRvLRLFvvbLLFQdHMTHTlQlNqNmqFlWdH"
        "vzjzvHtcHvJcDStLLGSShCbbfF"
        "MWFFTVZRMmMgdQdSQLwQrQwbGw"
        "gFTmgmVZssRsWZRNzJlBHHnnJDvzNPlP"
        "rHrvHpmHZfdGDDGGZd"
        "cTlMsNhllMhGchNPCBlhMQgVDdgDSSWVbWVwRQwRSgbV"
        "lnBjnNNTTMnCTcChPNhMvtzvFGLtJrjFtHHHzHJm"
        "lgpdZZMmGVVzVZzt"
        "HfHLrHqbPbzJJzRJJPTl"
        "HsLWWbDqFrqlqfbsbDqDBncpgFmmvpnmmgpvdvjcdM"
        "GpNVbTpJJNvMBMVvJTGvhnWQQScllnhhWlhVSznV"
        "ZjswwHHLZzGnjWjSjl"
        "sHdftLLtgLfwdtPmHtMbNpMTpNqGRbPvTqPv"
        "sHSNNhNwsllGSGGlWSGWSsFrrVbQrdmFrVrrmnrHmrHr"
        "QQMRZDDRcrcnmRcV"
        "fJfCPMJCzTMZSGsWwsWBwqQf"
        "HwQZZJsHdqqsdJQGRgCgVGgSqgpcGG"
        "ljWWbnPhjBlGpCRCnScSGg"
        "hrrztWlbPjltjMPSdJDZSsHttwsZwD"
        "VzzbmzvpvNhvBDqc"
        "QHSJSQGCwJCGrGQjjcgcBFhdgqdqFdDNNw"
        "rCGJtZrHhhtLRsth"
        "TMWwCLPpMTThrvtMRJjbjRvmJs"
        "fDzcHFfSfFQfZzZRJbdmmqqssqtbSW"
        "WWgGZglcllgPBBCBNVGPNr"
        "wrwwhpTpbqhqrshrrfrFfwfzRJGdNJHNmcFzCCzCRJGzGR"
        "vMggvjQvgPvQjVLMMPSZqWNJGCzcNGdcdzHPPzcmCzPz"
        "qDZWvBZVfDhbTtrp"
        "LpDvHdjVghnjbGrn"
        "FBBBPwwlBlwSfFTWPHPWWhmgngmmnPnmbsngngbGrb"
        "FwftBSCSfWCtwfVQDvHHCMVvdQLQ"
        "ZrQpQlSpNlqQCVnQBmdDqmWDqmWWBDBB"
        "HsZMsJvZzLMHTRwWhgDwmfDBgdhWdf"
        "RZvTzJGzRjFrVNVjlQrS"
        "mqjMwfqlSSPmSrlPhwhVpGRcppWcpcGRcGWv"
        "ssJDJJNgZNDWrRWcRpvr"
        "ZTsTnnsLJQgPnfMwmnMrfm"
        "qsVBvZqWLdfbfvLj"
        "mPNRgmHBBGQrCbSbrdfCCSbC"
        "PlQTGcTTcgGFQQGPTGllpqMzwzpVJZwBMssZ"
        "FWGcNRLRLhwJJQfV"
        "nzbzlDBHSpTDbpDpzHwCqhqwJJghQqQMCCBw"
        "JnzndzpmJFmNsrrFsc"
        "gmRwwDwfnRDJgwZLFQFFNGNQrFBmFbbm"
        "CCVHVWWThSrjVGvbNj"
        "WpdqpplppHCWzlClMMTTZJcJsdscJLLdbDDfZDgL"
        "VNtCCMDllpBqDvtdCczTSgjHlzGSHSGZTZ"
        "hPFPsQhhFhLnbsRnLFssdzcHdsSHSSHgjzHG"
        "QPWPQrPPmbdnbWLFPrrBVrVDBqqNMVwttDtBvD"
        "PPNNRggwgRRgHBhDtwhTwbDs"
        "SFGSFSMCJFMrcrCMSSsbtrTbbZhBvtHhrTHD"
        "MFfSMpflQLQflfLjnLmddsLdddqq"
        "RcgbcrrFscVrwZVCgVGGmHppNNndWnGdNqddqqNqND"
        "jTlSTBSTjLTvlvjjPtvMLlhHnftphtDFNFqDnDHWNddn"
        "QBMQvzzjzvJPjFQMmwZJrgmCCJVRVbbc"
        "CzPJsWCpvsNszsJsNsHlDhMrrJGjhrRVhRGgDDjG"
        "tFFdbqFLFdwctQdfVhjRRghTcrjVRTDW"
        "bwQtFLdLBdFmwnHnWHPBNnHCnp"
        "CNTstGNslRRRstlmNmmTZZqfFwtqgwqgfBPSwSWwqgWq"
        "hpDbcHbpSrcgqqzhhWVfqg"
        "DDcLDjbMjCSsZRNlMv"
        "MhHMCMNbzbMHlcqmGmrmWc"
        "tnPggdZPBPgdtttJpdnwVBnmqQcvlQrQlfGqmfWffBcqWD"
        "VPPwPPLPwLGFGLzCbG"
        "rqBcBmjHTGfPbcVgPG"
        "dlDpsdshzlldlDvsWlWvLQbQBbfLFLbPvbBGQBgG"
        "BlBznnRWzlphphBnhZjZtNNCNmrNqjCqHwHN"
        "mQBvmvBmmLJvvrLtttQrfhGlcRGfRhVGWJVChlRG"
        "MzPswTsbTPPsNgMNszgzMpbMfcRcGflVGRfWSpFRlWWWFhcC"
        "bcPsTbgbbTTwNZzTZzvdjdjtQQndZvdrvdmZ"
        "hQzTQJFFZJrcdcdZFFrGFSVWVRWRwRgRHVMWDCDSWc"
        "lPmpNBnnnsNBnLnfbfnCDWMvwRvDCCMPwwHWvM"
        "HpjmffNlnqqhddTddFZjGJ"
        "BwsLFFbHLbVCSCSFbsbFLsJbqnTtZrRMHTZtrTrZTcRRRRTq"
        "lGhNhpPmmhpztZTBrcpjRqpB"
        "QPzdfzBQNgFJSCwsdLbS"
        "ZsZsSBTgffSCqSSfrMnnMwjqmqmnnnqwMm"
        "bbPPbzVclcPzGNlvzVtmnDBnQmtnQLBjJVLn"
        "zPFGplGGvdPbHplcbzzvdlNBTThgRpCTCTfhfsCCsSRZhR"
        "CVLSVCLVZRsHcnzSRpdZZRCdPlmcMWDDlPNqMqtDMmqPMlDt"
        "TBnGjfQrQJjhfWlPPmPQDNlmlP"
        "fjhhGvjvvrTTBhvTBTbvGVRLzVnbSRZpHddspHRzLs"
        "DDtWjfRfftWMLzSQjzzhWjjwRVPHqFbBbZHVwZBFvFwZvZ"
        "JGllgCJlJsrCGPrCNTPdslvZVVNVbvBqNbbpbbFHpBwZ"
        "CcPdnCdmCJjfcftWhtSL"
        "pgpfddDGHWzDNGNGpRCQjCTFHZZQFQjcRT"
        "bJlhqmMvnlrRQFtTthPVhZ"
        "lvbJrlJMBwfzGNTddB"
        "wpbJGGZpsjvtdWvGWF"
        "HqqhBhBqhhNQHTSHqqNzRHVPvTvddWrjtrjFvrvdTdVP"
        "NRLCRzlqHQtNRBLzQllhhZcgbggwmLDZpsgssDpwwD"
        "pDzFzJFcVMcWJFJFzpLBsqWLZssshsGLGbsS"
        "wqHqfvnfrRwQtdQRthhBbBbZLhPLnBTGsh"
        "CfQqlqvtfHNvMVmzmmMCFDMc"
        "GcgpNHvcSNvpSLphdhsLdQTsdWThhQ"
        "wwzttPrrhQswdhnT"
        "tjJjMJRbRbjztmjtjbgcRsNlgglHpDFSlSvg"
        "VVLvLqqPVlvcqLLdwLbHpzcHSsbRJppHbHpF"
        "CfjjCNGmMWhWjhWHWb"
        "ZmGZffggrDqZvZtlbTqL"
        "TTmmhvBvvHWzHpsPpstpLVdwwsLb"
        "qflfFgNctNcCnCCNDnfFFNDwrslwZbPswwZbJLJZbrlPLL"
        "FgQDDcncStCgtqccjSDTHWMThvhTQMBQhWvWRG"
        "SqhVghPccSBhgSBqWBFNQNsHQHMjCCQQWCwQHN"
        "fLZftnlttcbbtZbZlpZtttQjwsCQjRwwRDQspMRMNNQs"
        "TfLtvbJtZmlbTTTtlJbFvVqPSgBdPqPhFSGBcd"
        "pPPNDptcqtpcDztLDhhngnnJgJTmJwNnwm"
        "HVVCsSClHGBCHslWHbSCGGVngTrJwnnJnQRRBrhQhgJhdm"
        "WTWWWsvVlvGbWCFvjDftPpjqZLLtDz"
        "wWclwtDwRvflvffB"
        "sMMsGdsSTMrJZNqczfdvhvnzCnfv"
        "rspppMjMspSTSMpgLjcPFmwPLmPHwb"
        "tCdSMHtHtRFHdWSSJQSgrrrnghTNJN"
        "BGfcvDsfvsqcvqfGvfGnNLhggBNQJNJQmpgQJm"
        "sGfQDPDZzfDZzclwDzwsDlfjtbdHClFRCMWjbMFMRFWbdj"
        "pJNCcvqCccsVvFCpqsmvWJfCBWgSzBBRrrBRDDgDrSbbgQbQ"
        "TMLnLjjffwfwGdjQjDDBjBrDtztRSb"
        "MdPLGhHnMZhlPHHTFfZvVCpmmmcFcVFC"
        "SwFMfCMRCdQDdMbmdFfdbbnlcVncVCcgLqWcNNnCcWlW"
        "hPjQzzhGzhpPrtPJPpPHrVgnqVVncVVnNHlqVnncNB"
        "ptjGrptztpthtrtJJhTsGwFDZZDQmSdfZSwsRZSwfZ"
        "rSSWWCWrdllHWpjcnFNnRCNjQp"
        "bGwwJqGVGbGJVVhgbBgttGmBQjFsMjpMcMnnMBcQFNnsssvv"
        "bfthwmfJfgwwmmwZqVJPHNHSZHWzSlDPrdDdSH"
        "nmJccvclcbwmlbbvVbvsHwJJPCPNCNPnLBhrBPPLBhLhBgBP"
        "MdRGtdDRTqWDMqtMDtQDRWSdLLBsrhLgBCgrgCgNNLPBfNMf"
        "dRZQdDdRRSQWGsjZmwzjmlzsZH"
        "PBGGMrTQTrTBpPQpLpSlwjwfjtlnfwbmGttw"
        "fCsJCWJcvRCtwwjbCl"
        "NsqcsfcvDHFVDJvdLQTrpdTTzTPpHr"
        "rltrwsBTlrfGZggGBLGGNN"
        "jhMnRQJVphMnbhvQjDZNqqZDNTNHZVHGHq"
        "MRvbhQRQQChpvbjvMSvQnMcsFsfwwmlCwFwWcTWwrmPc"
        "DDvLLLBnvrzvbvbmtv"
        "TMwRjTRMGCwGGwrjQQnmrQrrQdhZ"
        "MJPFHFTwgCGqGqgJMGDfSWcsnBSccgVDlnpW"
        "flzVzNrdLNLJzrGlfdlzjrQDgFTpDgDmmmgFmqFDQjQh"
        "CbnBcsZnPZVSnwvVsZbRhhBDpgFphgmgDgTppq"
        "ZWnsWSnncSZsntZCbsswwJMzdLzlMdNMLtMVfrllMt"
        "ZffSgNfgJgGCHZcZrpHrNJTLhqvSLTqQnvVTLvzvLTjV"
        "tWFtHMwlBlDqjjzjnqvvlV"
        "DRMPDtWHPFDBFFwWMFBmFRPgZpJfsffNGJNrGcsprrsmfg"
        "wRZRmpZmlPqZjzGrdrGq"
        "bBhQQFPQbPDVNzVNzdGWNdrf"
        "QFbcDcDbLHgHBPDFRsSSMtmvRttMpCLS"
        "MpWJVVJMcWvpRShcwpLGflmqzSfNdfNLdQzN"
        "CDBTtCgtbjgCRrBrPBTQqzflNqjGdLzzmqffzq"
        "rFgnnBbttDTPtHCDPrPMnpwVJhJvMZvpMvppRZ"
        "sWTTmpsfsWppPTTsTVZWHVVZNvVcdcJvdN"
        "DjjBzjhRHvvvSzdc"
        "rMBjjrjbjrGDlgMlMrGjBgRLPTTwHMsfnFwFQPMPMnmFFm"
        "QRRbDjjmPzNQwFDNmrQmzCbVHrMhBVrJLJJfMGGLtfJBHh"
        "dsWcsqqWSWvnWnWcWGPJLBqhLBqGhBJHHH"
        "ZWnPWgWgPnlbCDDwmmDbRZ"
        "nfPqqfLqQnfHBSqnzztQjVmjfGRWJNGRWsJWJfmJ"
        "TTMlMMlFDMGVGRsVJH"
        "CbDbFDbvgTFFwgTDlDprhlPSqBzSnPdLPtPPHgznQqBQ"
        "fJmWVfHqjfjhZCQZ"
        "NcNzBNvgszQmzjnthZQC"
        "LsLsgBNFmFgTFgGBBgcdMdvPDPDJWrlpVbGpJWqHDlHJHD"
        "SllDdvzgdFDdlPJvbFDDSzFScPTRTNcwfZRwRhcwwNnRZTtf"
        "WBpWBCLGVpLjHrHGGVhZNwcTVcNhVnRcNZ"
        "LHLQLspHWQGpWCHnBvdzDJFlqvdsqgSgqS"
        "GcTctDMjMhpMDRjLsMMsfDWFfdPCFNbnCPnvCPgW"
        "JmvwqlBwnmfdFPFP"
        "SvZqHSZqqHZZZBlllBwSwsRsMHpLjpLsMGtsMspGRT"
        "ClLnCLfClLVllfLLcQjLBCfCmSHVsttsmtsVStDNVdppdsSp"
        "PFrRMbWqMRwFRqRSqwqvMvMsGtgsdmssrgNtdmpNdDGgdt"
        "bwJbPWPwFFPFSczCZzZZCcfjBJ"
        "MwmBmzwJQTcTmfPVfZPwhhwHPH"
        "jlnrglFLvbrGRFGnvFZdNNFfPZddPThVhdPH"
        "RjbjpgbnLGvpLgzBqBpmWmmzqTMS"
        "FnsSpttPnPbNCFDtsPnFHQZTQZgcwgDDTfrfTHMZ"
        "mRjzRzlvBvhjZrQmMMwfZZNN"
        "ldzddlzLRlRWdhjdRLjhRWtJbJbNtJJpJPbCbGCWNG"
        "wBwmNZBTmzzcVcmpzZqdMgPjnLSVlPgDPdbMdg"
        "flJvGtHffHDddddbHjnb"
        "RstrhfrhhRGFQtRhtftvQhvFZpsmpWwNlWqcWTccBNWswqNp"
        "DPWhbzDlQLLlQbLDlLhPhLFNNJqCFGqnNJCCSCnGPnGN"
        "wvwjtvtdwfssvSJgFFvGGSCFcp"
        "mtdrZwwJsrtddrHRtZWbVThLlBzVTzhHQWhB"
        "TsRRWctsTJMQZllggc"
        "zDvhpbprgGvpvVlVQlZpQMJVlQ"
        "rrrvFvGCDhDSrrrvChCgSstBNTSftWBjTdfWBN"
        "JJdssBcLVGrgbBHWrH"
        "QZTptvmvmlZpRDlMMMZCQvnjjFnrjWGFbjnrnFGWgZrz"
        "TMRplDMggtwlppTlvhsJJqdcqwVPSSNcLd"
        "JjTCCrcRvccPLmMP"
        "NfGFPZlNnwBfPlbbbQZGqLHgzLghSmMBzSgvzmDMhv"
        "ZfbnNQpQnZGlGlGpWTddjdTJdpRPTrCj"
        "gWLblMMggdWsdRJlblMRMMqWDvPvcPPPccJPJVTZVZThmcDP"
        "rQFfGfrCHrjnrtNTcPShTSPvvVLtmm"
        "fQrCfLrpLHnCHwslqzqsslswzqRW"
        "zpJtGlJPMPTlTjGJCDGCDljpdnvhhWnZnZnDwwmvnWDWWvdd"
        "sHrVrSrRRRLNgLVBqSsZmWwvwcvwZjmwngmdbn"
        "QsQQBrrLHTjPpTQzzP"
        "JDlzHHzzptRDmbTMrrVQ"
        "dRRNqnCBnmrQsVQQ"
        "wFPCBNFgwjPwhgFNztftpJRPpzRvvHtZ"
        "DlBhrDBPPwMWwhWchW"
        "ntSqbbSJFJNqzVzjCfMvfSlSRWccRL"
        "mVlHtNVtqldbJVmNHmdTTBBgrQQgGsPQdrDgsP"
        "HWHNbBgvNLdcvQMnSf"
        "wqqqVPDPhqwszFwrrszFfMdWthLcMdfhthSQfJSt"
        "qVPVwTzFwFDpDrPDzDPFDPlCHjBGjTmZGjbWWGZBRTNjjH"
        "GVgdWjllSqgjdgHqqlfmhwcpwCzhvZwMcScv"
        "nsJQbLRQsNnzQDQQPPBbRBRhfZwpZcvwpvvmLCcvpcmfMM"
        "DRJtnnRbBBnPztsrPzRBPbsFFHqqVrqggjFWqrgWjTGgFq"
        "hhZJQPJFHGGlcWWslpNN"
        "VwwwJjvwMtrCnwjDNDzlfscWszWW"
        "nVStCrMqbVwqVqSqwnLPhTJFdRgJHZSFRLTP"
        "vPgMbbRhhvMvNjjLWsWQsHQmHwBrmmBzww"
        "tFctDnVFpppHVBTdzdTQwl"
        "FtSFqSptfJCqqJStZCqDpDJMhvLLgLMgQgjgGZgGgMPLZg"
        "zwsWgSGWLSVhPWhtLgLWhPVNQTmDrDQttZpdQtdpQDDQZQ"
        "fjCHcvvjMDrppCQpVV"
        "VMqRnVJMVLPzbRWhGh"
        "mjRmzQlzDzNHWwDZ"
        "FBfJBGqnnpfSVGnpJbJVfNtCsJHWZvrsNJCZrCNsvN"
        "fZPBnfPqSBqdfpFbVnVSjgdcLLgRLjmgRhLLghlR"
        "FSFnTcppdQtnnDhtzDfg"
        "ZLGVmBLBVwZCVjjGqGhVwVVgzzbMDtNNvszMmMffNDDvtM"
        "VZPJjBZVqBZZBjqwVqllpSTphhQFPShWSQcW"
        "hTRdcLrCLgplLvBFGvlL"
        "nZDZqzbDbDzRZtVNDzDWGwslsllBFpnlpGvJssFG"
        "zbqjNWQVmVPrrRjRdRhS"
        "VpNCbVHlHHZfflVfmchctqFcqQQjZmZM"
        "WDSRGgsSvgJSRrnWgqQhmjBqmhqrtLqmQm"
        "znSGTgDJnsDGzgwCwlpbCNwHzVtl"
        "sTTTrpHFFFqTnQbbvfJdDzHHDLVV"
        "CjMtgMgRvbPfjjvB"
        "mhMvlhhWClvqshNTQQqsNN"
        "tWFtFBzbwdFrpmdhdm"
        "qTqDjJjJQQqMjTDLJjNqNqPNdmpcSmhdmhhmcrWZpdPGddcc"
        "RjNQLJNTTJDDJRHHjQqnMWtlvvVvbtBvRVzgzgwgVg"
        "CGdQjwdJrbBmpmZZZlRWcb"
        "NgtMPVstgSzBLzhgzgLgDRlcmDWRmlZvcSmDSvvp"
        "LhNsgPPLFPPsNzMhhVzPsGJBFqwQGfnqfQjdGdGfwr"
        "CNbNdbzjCZpPNzjmzjsCMRJvnnMRGnsvJGRs"
        "wrtdwTLWFcFWdFgwRRsnJGnGfTGJfMsq"
        "FttcwgBtgVLgPldQSNZBzBpz"
        "DjRZrrRmttRFDvDrFTZsnWnHVSTSSJVZJH"
        "dNNhLqlLLqdCzfMMlCfSncTVVWcHdcVsVdSVnT"
        "QqppMfzMfqWCwbRQrwFrrttQ"
        "dwGjHrtjsdhfCHnPSpfMfDPpPDWS"
        "lmNzzlLbFqcqNgzpWMSvbbvDQDGWDp"
        "LBmglgmqBqmrwCGhCjVtBC"
        "tvHgWZCCprlgpWglCtjPhLmPmhVdJFSzVzdJVmmQ"
        "fBnTTnNNBnwfnNqcBbBBTbGJQQJhSSdQJJsmdJFSQGSmVV"
        "cMcDwFbRfFRlHCRCZrrp"
        "ZFWmgghzBgwgjWBzjzmRWWMmsVwnVrsdVdwNrrpnnVrPCnCP"
        "GLLbtGqllctqvGJvSlQbJGsPnVdsdpsTPLsVppBCTVss"
        "tJBStGSvctvDDfczmRgRZjzDjZmgzH"
        "FMrLmsQQSWzCZBhpQJTQQZ"
        "dPPVncVvPBJDCPhwJD"
        "fvHbbVHvqnvvvBzgLbbGGmrbMr"
        "mrZzrzqDrhZqDddSFrCGLLLPQPQBJPJJBnQq"
        "TgbpGblWlMsjgWlgMfpNRgbRHHBnHHHtLpCJPCPBnBLJtQQL"
        "sbTlblTlvRbbGblbFcdDzccVcDVvzzzd"
        "zMzfzlGwSBMMSCMzhsPgfcPcfcbhjQPt"
        "FHHqJVdJmFmdVrJdJppthscjGtqRPRcccgcQbR"
        "rvNJJpLrvvLnJvNFFvZZZBWznBWGSDCMnCwz"
    |]

let example =
    [|
        "vJrwpWtwJgWrhcsFMMfFFhFp"
        "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL"
        "PmmdzqPrVvPwwTWBwg"
        "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn"
        "ttgJtRGJQctTZtZT"
        "CrZsJsPPZsGzwwsLwLmpwMDw"
    |]

[<Test>]
let Day03_Part1 () =
    
    let answer = 
        input
        |> Array.collect 
            (fun line -> 
                let midpoint = line.Length / 2

                [|
                    line.Substring (0, midpoint)
                    line.Substring (midpoint)
                |]
            )
        |> Array.chunkBySize 2
        |> Array.map (fun lines -> 
            lines
            |> Array.reduce (fun line1 line2 ->
                line1
                |> Seq.filter (fun x ->
                    line2.Contains x
                )
                |> System.String.Concat
            )
        )
        |> Array.map Seq.head
        |> Array.sumBy  
            (fun found ->
                if (found >= 'A' && found <= 'Z')
                then ((int)found) - ((int) 'A') + 27
                else ((int)found) - ((int) 'a') + 1
            )

    Assert.AreEqual (8233 , answer)

[<Test>]
let Day03_Part2 () =
    let answer = 
        input
        |> Array.chunkBySize 3
        |> Array.map (fun lines -> 
            lines
            |> Array.reduce (fun line1 line2 ->
                line1
                |> Seq.filter (fun x ->
                    line2.Contains x
                )
                |> System.String.Concat
            )
        )
        |> Array.map Seq.head
        |> Array.sumBy  
            (fun found ->
                if (found >= 'A' && found <= 'Z')
                then ((int)found) - ((int) 'A') + 27
                else ((int)found) - ((int) 'a') + 1
            )

    Assert.AreEqual (2821 , answer)